export enum FEATURE_CODE {
  LOGIN = 'LOGIN',
  TRANSFER_MONEY = 'TRANSFER_MONEY',
  TRANSFER_DOMESTIC_BANK = 'TRANSFER_DOMESTIC_BANK',
  TOP_UP_MONEY = 'TOP_UP_MONEY',
  BILL_MONEY = 'BILL_MONEY',
  CASHOUT = 'CASHOUT',
  DATA = 'DATA',
  BILL_INTERNET = 'BILL_INTERNET',
  CHANGE_PIN = 'CHANGE_PIN',
  REGISTER = 'REGISTER',
  WITHDRAW = 'WITH_DRAW',
  CASHIN = 'CASH_IN',
  DATA_MONEY= "DATA_MONEY",
  CASH_OUT_MONEY="CASH_OUT_MONEY",
  USER_SCAN_QR="USER_SCAN_QR"
}
