-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgX7ABOR9ZerXnjFyQ
UoHRHEGXYSeAIrDo+n+HrxJmuxagCgYIKoZIzj0DAQehRANCAATUa6ogvgS5s4q+
8o3H+6zVohvdS5ZnPj3y2gO51wX6jpOVm2hGlpaPdFGbg3IsX4gjnPGCp4dWiUWm
Lk5gEnKU
-----END PRIVATE KEY-----